config/routes.rb
XephangFacebook::Application.routes.draw do
  resources :pages

end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/page.rb
require "net/https"
require "uri"
class Page < ActiveRecord::Base
  validates :name, presence: true
  validates :uid, presence: true
  validates :json, presence: true

  before_validation :get_page

  def graph_url
    "https://graph.facebook.com/#{translated_url}"
  end

  def image_url
    "https://graph.facebook.com/#{translated_url}/picture"
  end

  def about; data(:about); end
  def description; data(:description); end

  private

  def data key
    JSON.parse(json)[key.to_s]
  end

  def translated_url
    URI.parse(url).path.gsub(/^\//, "")
  end

  def get_page
    uri = URI.parse(graph_url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)

    if response.code == "200"
      self.url = translated_url
      self.json = response.body
      self.name = data(:name)
      self.uid = data(:id)
      self.last_likes = data(:likes)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @page }
      else
        format.html { render action: 'new' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Xep Hang Trang Facebook
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    .container
      = yield

app/views/pages/_form.html.slim
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      h2 = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      ul
        - @page.errors.full_messages.each do |message|
          li = message

  .field.form-group
    = f.label :url
    = f.text_field :url, class: "form-control"
  .actions = f.submit 'Save', class: 'btn btn-success'

app/views/pages/edit.html.slim
h1 Editing page

== render 'form'

= link_to 'Show', @page
'|
= link_to 'Back', pages_path

app/views/pages/index.html.slim
h1 Listing pages

table
  thead
    tr
      th Uid
      th Url
      th Name
      th Json
      th
      th
      th

  tbody
    - @pages.each do |page|
      tr
        td = page.uid
        td = page.url
        td = page.name
        td = page.json
        td = link_to 'Show', page
        td = link_to 'Edit', edit_page_path(page)
        td = link_to 'Destroy', page, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Page', new_page_path

app/views/pages/new.html.slim
h1 New page

== render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.slim
h1= @page.name

h2
  = number_with_delimiter @page.last_likes
  | Likes

= image_tag @page.image_url

p= @page.about

p= @page.description


= link_to 'Back', pages_path